image: python:3.8.10

dependencies:
  stage: build
  script:
    - apt update && apt install -y graphviz graphviz-dev
    - python3 -m pip install doit pygraphviz import_deps
    - doit
  artifacts:
    paths:
      - dependencies.png

pytest:
  stage: test
  before_script:
    - python3 -m pip install -e .
  script:
    - python3 -m pip install pytest
    - pytest tests

codestyle:
  stage: test
  script:
    - python3 -m pip install flake8 flake8-docstrings mypy==0.971 isort
    - bash codestyle.sh
