image: python:3.11.11

codestyle:
  stage: test
  script:
    - python3 -m pip install -e ".[dev]"
    - python3 -m mypy ipcv_tools examples --ignore-missing-imports --disallow-untyped-defs --follow-imports skip

pytest:
  stage: test
  script:
    - python3 -m pip install -e ".[dev]"
    - python3 -m pytest -v --junitxml=report.xml tests
  artifacts:
    when: always
    reports:
      junit: report.xml

dependencies:
  stage: deploy
  before_script:
    - apt update && apt install -y graphviz graphviz-dev
    - python3 -m pip install pygraphviz pylint
  script:
    - pyreverse -k -my -o png ipcv_tools/**.py
  artifacts:
    paths:
      - packages.png
      - classes.png
